### PR TITLE
fix build error

### PR DESCRIPTION
**Pull request by JacksonYao287**
1 set c++ standard to 17 to enable some libraries since c++17
2 fix some syntax error

### CODE REVIEW

**Review by szmyd — APPROVED** [review]
Success in CI: http://sdsbuild01.lvs.qa.ebay.com/blue/organizations/jenkins/HomeReplication/detail/PR-21/1/pipeline
LGTM

**Comment by yamingk** [comment]
Can you share your compiler err messages?

**Comment by JacksonYao287** [comment]
> Can you share the build err messages?

https://drive.google.com/file/d/1kpBW64rIiOBweU2X6qgdvxO6k6PJfhwE/view?usp=drive_link

**Comment by zhiteng** [comment]
> > Can you share the build err messages?
> 
> https://drive.google.com/file/d/1kpBW64rIiOBweU2X6qgdvxO6k6PJfhwE/view?usp=drive_link

This doesn't look like a public sharing.  Next time you can use something like https://pastebin.ubuntu.com/ to share logs.

**Comment by yamingk** [comment]
> > Can you share the build err messages?
> 
> https://drive.google.com/file/d/1kpBW64rIiOBweU2X6qgdvxO6k6PJfhwE/view?usp=drive_link

it shows no permission for me to access above link, if possible, can you paste the logs here, also can you also provide more information of your building evn, e.g. are you building inside sds_dev docker or on linux alone, gcc version, etc. That can help reviewers understand the problem. Thanks.

**Comment by JacksonYao287** [comment]
截屏2023-06-08 11 59 23

this is my local building env. 

the build error log is https://pastebin.ubuntu.com/p/hCFwjtSYZN/plain/ , PTAL!

@yamingk the build error log is too long to be pasted here. if you can not open the new link, please let me know and may be i can send the log to you through slack.

also , thanks @zhiteng for the advice to publicly share docs， pastebin looks very awesome！

**Pull request merged**
